# Static and Dynamic Factor Models

## Capital Asset Pricing Model (CAPM)

The CAPM can be stated in both the SDF space as well as in the return space.

- In the SDF space, we have:
  $$
  m_{t+1}=a+bR_{t+1}^{W}
  $$
  where $a$ and $b$ are free parameters.

- In the return space, we have:
  $$
  \mathbb{E}\left(R^{i}\right)=\alpha+\beta_{i,R^{W}}\left[\mathbb{E}\left(R^{W}\right)-\alpha\right]
  $$
  

**Derivation**

In the simplest possible case, we can show that two-period investors with no labor income and quadratic utility imply the CAPM. Since quadratic utility assumption means marginal utility is linear in consumption, we have:
$$
m_{t+1}=\beta\frac{u'\left(c_{t+1}\right)}{u'\left(c_{t}\right)}=\beta\frac{c_{t+1}-c^{*}}{c_{t}-c^{*}}
$$
The budget constraint is $c_{t+1}=W_{t+1}=R_{t+1}^{W}\left(W_{t}-c_{t}\right)$. Furthermore, two-period implies that investors consume everything in the second period, which allows us to substitute wealth and return on wealth for consumption:
$$
m_{t+1}=\beta\frac{R_{t+1}^{W}\left(W_{t}-c_{t}\right)-c^{*}}{c_{t}-c^{*}}=-\frac{\beta c^{*}}{c_{t}-c^{*}}+\frac{\beta\left(W_{t}-c_{t}\right)}{c_{t}-c^{*}}R_{t+1}^{W}
$$
Another case is when $u\left(c\right)=-e^{-\alpha c}$ and returns are normally distributed.

## Arbitrage Pricing Theory (APT)

The APT states that if a set of asset returns are generated by a linear factor model,
$$
R^{i}=\mathbb{E}\left(R^{i}\right)+\sum_{j=1}^{N}\beta_{ij}\tilde{f}_{j}+\epsilon^{i}
$$
with $\mathbb{E}\left(\epsilon^{i}\right)=\mathbb{E}\left(\epsilon^{i}\tilde{f}_{j}\right)=0$, then there is a discount factor $m$ linear in the factors $m=a+b'f$ that prices the returns.

**Informal Derivation**

1. **Assume a linear factor model for asset returns.** Specifically,
   $$
   R_{i}=\mu_{i}+\beta_{i}\Lambda+\epsilon_{i},\quad\mathbb{E}\left(\Lambda\right)=\mathbb{E}\left[\epsilon\right]=\mathbb{E}\left[\Lambda\epsilon\right]=0
   $$
   In matrix notation, $R=\mu+\beta\Lambda+\epsilon$.

2. **Construct an arbitrage portfolio.** This is a portfolio such that the weights $w_{a}$ sum to zero $\left(w_{a}'\iota=0\right)$ i.e. there is no net investment. Then the return on the portfolio will be given as 
   $$
   R_{a}=w_{a}'R=w_{a}'\mu+w_{a}'\beta\Lambda+w_{a}'\epsilon
   $$
   If this a large enough portfolio, $w_{a}'\epsilon\approx0.$ So we can further choose a portfolio such that $w_{a}'\beta=0.$ Then the portfolio has $R_{a}=w_{a}'\mu$ i.e. no idiosyncratic risk and no factor risk.

3. **Impose no-arbitrage condition.** This implies the above portfolio must have zero return, i.e. $w_{a}'R=w_{a}'\mu=0$.

**Shortcomings of APT**

1. We know that some portfolio is always mean- variance efficient ex post. Thus we know that ex post, we can always get a single-factor model to fit the data if we happen to choose the ex post mean-variance efficient portfolio as the single factor. It must then be even easier to get a K-factor model to fit the data. This does not tell us anything about the world unless we can have some confidence that the K-factor model holds ex ante as well as ex post. In other words, we need theoretical reasons to believe that a K-factor model is structural.
2. APT does not determine the signs or magnitudes of the risk prices.

## Intertemporal CAPM (ICAPM)

The ICAPM states that risk premia depend on covariances with market wealth and with state variables that determine investment opportunities and/or future labor income.

Specifically, the ICAPM generates linear discount factor models of the form:
$$
m_{t+1} = a + b'f_{t+1}
$$
in which the factors are the state variables for the investor's consumption-portfolio decision. Current wealth is obviously a state variable. Additional state variables describe the conditional distribution of income and asset returns the agent will face in the future or “shifts in the investment opportunity set.” 

**Comparison to APT**

As a multifactor model, the ICAPM and APT are similar. However, APT is silent on what the factors should be, whereas the ICAPM states that the factors should be market wealth and variables that predict future returns and labor income (or the projections of such variables).

The APT suggests that one start with a statistical analysis of the covariance matrix of returns and find portfolios that characterize common movement. The ICAPM suggests that one start by thinking about state variables that describe the conditional distribution of future asset returns and non-asset income. More generally, the idea of proxying for marginal utility growth suggests macroeconomic indicators, and indicators of shocks to non-asset income in particular.

## Conditional CAPM

The source of risk in the traditional CAPM is the fact that the value drops when the market goes down. This is the "market risk." 

In the conditional CAPM, there is an additional source of risk: risk exposure increases in bad times, i.e. the countercyclicality of the market beta (higher beta in recessions).

**Lewellen-Nagel (JFE 2006) Critique**

This critique says that the variations in betas and the expected market risk premium are too small to make the conditional CAPM successful in explaining the return differentials between different groups of stocks we observe in the real-life data.