# Pricing Government Bonds

## Overview

### Treasury Securities

Treasuries are issued by the U.S. government in regular auctions in a range of tenors, broadly divided into bills and coupons. Treasury debt is auctioned by the New York Fed to primary dealers, who then resell the debt to their clients. **Coupons are auctioned monthly in sizes that are announced at the beginning of each quarter, while bills are auctioned twice weekly in flexible sizes.**

The most recent issue of coupons is called “on the run,” while coupons issued from previous auctions are called “off the run.”

- On-the-run coupons are very liquid, but become progressively less liquid as time goes on.
- An owner of a deep off-the- run coupon can still instantly borrow cash against the coupon in the repo market, but would have more trouble selling it outright. This makes investors of coupons a bit more cautious, so while bills can be elastically sold, coupon supply sticks to a schedule.

### Agency MBS

Agency MBS are mortgage-backed securities guaranteed by the government. Mortgage-backed securities are bonds that receive the cash flow generated by a pool of mortgage loans. The government can either guarantee the mortgage-backed securities or the mortgage loans underlying those securities. 

Agency MBS have minimal credit risk, are very liquid, and have returns that are slightly higher than Treasuries, so they are very popular with conservative investors like insurance companies and foreign central banks worldwide.

The Fed has been an active buyer in the Agency MBS market since the 2008 Financial Crisis with the stated objective of supporting the housing market and placing downwards pressure on interest rates.

#### Fannie Mae and Freddie Mac

Fannie and Freddie are the two giants of the mortgage bond market. They support the U.S. housing market by buying mortgage loans and packaging them into securities that can be sold to investors. The loans underlying the securities are guaranteed by Fannie and Freddie, so investors don’t have to worry about any homeowner defaulting.

Fannie and Freddie offer commercial banks the additional option of selling the mortgage loan, provided the loan meets certain minimal credit standards. This additional flexibility was designed to encourage commercial banks to make more mortgage loans since they always had the option of selling them to Fannie or Freddie in case they needed to raise money. This created a robust secondary market for mortgage loans and also made possible an “originate to distribute” business model where mortgage loans were primarily originated to be sold rather than held as investments.

Today, most mortgage loans are originated by nonbank mortgage lenders who specialize in the “originate to distribute” business model. These mortgage lenders take out a loan from a commercial bank, lend the money to a home buyer, sell the mortgage to Fannie or Freddie, and then repeat the process by taking the proceeds from the sale and lending to another mortgage borrower.

- Nonbank mortgage lenders make money off the origination fees, not the interest from the loan.

Fannie and Freddie take the mortgage loans, add a guarantee onto them, package them into securities, and return them to the mortgage seller to be sold to investors. A guarantee from Fannie and Freddie make the mortgage securities virtually risk-free.

When house prices crashed in 2008, Fannie and Freddie had guaranteed around half of all the mortgage loans in the U.S. The mass foreclosures following the crash quickly made Fannie and Freddie insolvent and compelled a government rescue. Since then Fannie and Freddie have remained in government conservatorship.