# Demand System Approach

The materials presented here are a summary based on Ralph Koijen's lectures.

### Asset Demand System for Equities

#### Motivation

There are some questions that traditional asset pricing theories are ill-equipped to answer. 

- What is the impact of QE on asset prices?
- How effective is ESG investing in affecting the cost of capital?
- How does the capital regulation of insurers affect corporate bond prices?

Looking at Euler equation of a class of investors is limited because it does not impose market clearing, and existing macro-finance models may be helpful but they end up yielding counterfactual predictions.

#### SDF and Demand System Approaches

Any asset pricing model that starts from preferences implies (1) an SDF that can be used to price assets using $\mathbb{E}[MR]=1$ and a demand system $(Q_i(P),S(P))$ that can be used to price assets by imposing market clearing: $\sum_i Q_i(P) = S(P)$. 

**Demand system approaches can also offer more powerful tests.** With the SDF-based tests, we form a time-series average of $$M_t R_t$$ and see if it equals 1. In reality, returns are volatile and SDF is also very volatile, so this test is quite challenging. Demand curves, on the other hand, depend on ex-ante information and can provide more powerful tests of asset pricing models. For example, the asset demand from CAPM is $\gamma^{-1} \Sigma^{-1} \mu$ which can be computed before we know the prices.[^1] 

[^1]: In insurance: to what extent are people uninsured? Is it because of bequest motives or is it imperfect insurance? The old literature looked at the dynamics of consumption and wealth realization and it was difficult to get at the bequest motives. A more powerful test emerged, however, where one would look at life insurance purchase decisions.

#### Demand Elasticities in Standard Asset Pricing Models

All models imply downward-sloping demand. Petajisto (2009) provides one stylized model with CAPM for a basic calculation. The punchline from this model is that the demand elasticity $-\frac{d\ln Q}{d\ln P}$ is really high, i.e. even when an investor buys 10% of the shares outstanding of an individual stock, prices go up only by 0.1 basis points.

Why is this the case? Stocks are very close substitutes -- what matters is a stock's beta and its contribution to aggregate risk. 

### Macro Finance in Inelastic Markets

